### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by d1k0b3o** [nindanaoto/nindanaoto.github.io#16]
https://github.com/nindanaoto/nindanaoto.github.io/blob/e6f37279f58abc0c84ea4232288e6804d18c77e7/seccamp/html/2021/1.TLWE.html#L362

as is: Inteber
to be:  Integer
```<li>よく使われるのはTorusではなく剰余環に値をとるInteger LWE```

**Comment by nindanaoto** [comment]
修正しました
